#!/bin/bash -x
echo "welcome to ShortingArithmatic problem"
read -p "enter value for a" a
read -p "enter value for b" b
read -p "enter value for c" c
num=$((a+b*c))
echo "$num"
num1=$((a*b+c))
echo "$num1"
num2=$((c+a/b))
echo "$num2"
num3=$((a%b+c))
echo "$num3"
declare -A dict
dict[num]="$num" 
dict[num1]="$num1"
dict[num2]="$num2"
dict[num3]="$num3"

