#!/bin/bash -x
echo "welcome to ShortingArithmatic problem"
read -p "enter value for a" a
read -p "enter value for b" b
read -p "enter value for c" c
num=$((a+b*c))
echo "$num"
num1=$((a*b+c))
echo "$num1"
num2=$((c+a/b))
echo "$num2"

